version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dii_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dii_dev
      POSTGRES_USER: dii_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dii_secure_password}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dii_user -d dii_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dii_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@dii.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: