name: Context Management System Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # 8 AM daily
    - cron: '0 20 * * *'  # 8 PM daily

jobs:
  update_context:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for git log analysis
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Run context updater
      run: python scripts/context/update_context_simple.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Context Updater Bot"
        git add context/*.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update context management files [$(date +'%Y-%m-%d %H:%M')]" && git push)