name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd quick-assessment
        npm install
        
    - name: Build
      run: |
        cd quick-assessment
        npm run build
        
    - name: Prepare deployment structure
      run: |
        # Limpiar cualquier estructura previa
        rm -rf deploy
        mkdir -p deploy/quick-assessment
        
        # IMPORTANTE: Primero copiar Quick Assessment a su subdirectorio
        cp -r quick-assessment/dist/* deploy/quick-assessment/
        
        # Luego copiar el sitio principal (esto sobrescribirá cualquier index.html incorrecto)
        cp index.html deploy/index.html
        cp immunity-framework.html deploy/ 2>/dev/null || true
        
        # Copiar directorios del sitio principal
        cp -r intelligence deploy/ 2>/dev/null || true
        cp -r assessments deploy/ 2>/dev/null || true
        cp -r dashboards deploy/ 2>/dev/null || true
        cp -r framework deploy/ 2>/dev/null || true
        cp -r docs deploy/ 2>/dev/null || true
        cp -r data deploy/ 2>/dev/null || true
        cp -r scripts deploy/ 2>/dev/null || true
        cp -r templates deploy/ 2>/dev/null || true
        
        # NO copiar assets del root para evitar conflictos
        # NO copiar weekly-reports que no existe
        
        # Copiar otros archivos HTML (excepto index.html)
        for f in *.html; do 
          if [ "$f" != "index.html" ] && [ -f "$f" ]; then 
            cp "$f" deploy/
          fi
        done
        
        # Copiar archivos markdown
        cp *.md deploy/ 2>/dev/null || true
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
