name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd quick-assessment
        npm install
        
    - name: Build
      run: |
        cd quick-assessment
        npm run build
        
    - name: Prepare deployment structure
      run: |
        # Create deployment directory
        rm -rf deploy
        mkdir -p deploy
        
        # Copy main site files FIRST
        cp index.html deploy/
        cp immunity-framework.html deploy/ 2>/dev/null || true
        
        # Copy all HTML files except index.html
        for f in *.html; do 
          if [ "$f" != "index.html" ] && [ -f "$f" ]; then 
            cp "$f" deploy/
          fi
        done
        
        # Copy directories
        cp -r intelligence deploy/ 2>/dev/null || true
        cp -r assessments deploy/ 2>/dev/null || true
        cp -r dashboards deploy/ 2>/dev/null || true
        cp -r framework deploy/ 2>/dev/null || true
        cp -r docs deploy/ 2>/dev/null || true
        cp -r data deploy/ 2>/dev/null || true
        cp -r scripts deploy/ 2>/dev/null || true
        cp -r templates deploy/ 2>/dev/null || true
        
        # Copy markdown files
        cp *.md deploy/ 2>/dev/null || true
        
        # Create quick-assessment directory and copy ONLY the built files
        mkdir -p deploy/quick-assessment
        
        # Copy the built index.html and assets from dist
        cp quick-assessment/dist/index.html deploy/quick-assessment/
        cp -r quick-assessment/dist/assets deploy/quick-assessment/
        
        # Create .nojekyll file
        touch deploy/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy