name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd quick-assessment
        npm install
        
    - name: Build
      run: |
        cd quick-assessment
        npm run build
        
    - name: Prepare deployment structure
      run: |
        # Limpiar cualquier estructura previa
        rm -rf deploy
        mkdir -p deploy/quick-assessment
        
        # Copiar el sitio principal
        cp main-index.html deploy/index.html
        
        # Copiar TODOS los directorios del sitio principal
        cp -r weekly-reports deploy/ 2>/dev/null || true
        cp -r intelligence deploy/ 2>/dev/null || true
        cp -r assessments deploy/ 2>/dev/null || true
        cp -r dashboards deploy/ 2>/dev/null || true
        cp -r framework deploy/ 2>/dev/null || true
        cp -r docs deploy/ 2>/dev/null || true
        cp -r data deploy/ 2>/dev/null || true
        cp -r assets deploy/ 2>/dev/null || true
        cp -r scripts deploy/ 2>/dev/null || true
        cp -r templates deploy/ 2>/dev/null || true
        
        # Copiar archivos sueltos importantes
        cp -r *.html deploy/ 2>/dev/null || true
        cp -r *.md deploy/ 2>/dev/null || true
        
        # Copiar el Quick Assessment build
        cp -r quick-assessment/dist/* deploy/quick-assessment/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
