name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd quick-assessment
        npm install
        
    - name: Build
      run: |
        cd quick-assessment
        npm run build
        
    - name: Prepare deployment structure
      run: |
        # Create deployment directory
        rm -rf deploy
        mkdir -p deploy
        
        # Copy main site files FIRST
        cp index.html deploy/
        cp immunity-framework.html deploy/ 2>/dev/null || true
        
        # Copy all HTML files except index.html
        for f in *.html; do 
          if [ "$f" != "index.html" ] && [ -f "$f" ]; then 
            cp "$f" deploy/
          fi
        done
        
        # Copy directories (explicitly excluding any root assets)
        [ -d "intelligence" ] && cp -r intelligence deploy/
        [ -d "assessments" ] && cp -r assessments deploy/
        [ -d "dashboards" ] && cp -r dashboards deploy/
        [ -d "framework" ] && cp -r framework deploy/
        [ -d "docs" ] && cp -r docs deploy/
        [ -d "data" ] && cp -r data deploy/
        [ -d "scripts" ] && cp -r scripts deploy/
        [ -d "templates" ] && cp -r templates deploy/
        
        # Explicitly ensure no root assets directory is copied
        rm -rf deploy/assets 2>/dev/null || true
        
        # Copy markdown files
        cp *.md deploy/ 2>/dev/null || true
        
        # Create quick-assessment directory and copy ONLY the built files
        mkdir -p deploy/quick-assessment
        
        # Copy the built index.html and assets from dist
        cp quick-assessment/dist/index.html deploy/quick-assessment/
        cp -r quick-assessment/dist/assets deploy/quick-assessment/
        
        # Create .nojekyll file
        touch deploy/.nojekyll
        
        # Verify correct structure
        echo "=== Deployment structure verification ==="
        echo "Root index.html first 5 lines:"
        head -5 deploy/index.html
        echo ""
        echo "Quick Assessment index.html exists:"
        [ -f "deploy/quick-assessment/index.html" ] && echo "YES" || echo "NO"
        echo ""
        echo "Root assets directory:"
        ls -la deploy/assets 2>/dev/null || echo "No root assets directory (correct)"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy