name: Weekly Threat Intelligence Collector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM

jobs:
  collect_intel:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests python-telegram-bot python-dotenv
    
    - name: Run threat collector
      env:
        OTX_API_KEY: ${{ secrets.OTX_API_KEY }}
        INTELX_API_KEY: ${{ secrets.INTELX_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python intelligence/threat_intel_collector.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update threat intelligence dashboard" && git push)
